#!/bin/bash
IP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0'`;

mkdir /etc/VpsPackdir 1>/dev/null 2>/dev/null
mkdir /etc/VpsPackdir/senha 1>/dev/null 2>/dev/null
if [ $(id -u) -eq 0 ]
then
	echo -e "\033[1;32mNome do novo usuario:\033[0;37m"; read -p " " name
	echo -e "\033[1;32mSenha para o usuario $name:\033[0;37m"; read -p " " pass
	echo -e "\033[1;32mQuantos dias usuario $name deve durar:\033[0;37m"; read -p " " daysrnf
	echo -e "\033[1;32mNumero de loguins simultaneos $name:\033[0;37m"; read -p " " limite
        echo -e "\033[0m"
	if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
		echo -e "\033[1;31mUsuario $name ja existe\033[0m"
	else
        	hj=`date -d 'now' +%d-%m-%y`
		valid=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
		datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")
		useradd -M -s /bin/false $name -e $valid
	       (echo $pass; echo $pass)|passwd $name 2>/dev/null
		echo -e "User: $name	senha: $pass 	inicio: $hj" >> /usr/share/info/s
		 limit $name $limite > /dev/null 2>/dev/null 
		
		echo "-----------------------------------------------------"
    		echo "         USUARIO CRIADO COM SUCESSO           "
		echo "-----------------------------------------------------"
		echo -e "Usuario: $name"
		echo -e "Senha: $pass"
		echo -e "Expira em: $datexp"
		echo -e "IP: $IP"
		echo -e "PortaSSH: 443 "
		echo -e "PortaSquid: 80 "
		echo -e "Conexao(oes) simultanea(s): $limite"
		echo "-----------------------------------------------------"

	
	    echo "$pass" > /etc/VpsPackdir/senha/$name
	fi
else
	if echo $(id) |grep sudo > /dev/null
	then
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	echo -e "Ou execute o Usercreate como sudo. \033[1;31msudo Usercreate\033[0m"
	else
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	fi
fi
