#!/bin/bash
echo > /usr/bin/sete
echo '#!/bin/bash' > /usr/bin/sete
echo 'if which tput >/dev/null 2>&1; then
      ncolors=$(tput colors)
fi
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
    RED="$(tput setaf 1)"
    GREEN="$(tput setaf 2)"
    YELLOW="$(tput setaf 3)"
    BLUE="$(tput setaf 4)"
    BOLD="$(tput bold)"
    NORMAL="$(tput sgr0)"
else
    RED=""
    GREEN=""
    YELLOW=""
    BLUE=""
    BOLD=""
    NORMAL=""
fi' >> /usr/bin/sete
echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/sete
echo "echo '====================================================='" >> /usr/bin/sete
echo 'printf "${YELLOW}${BOLD}"' >> /usr/bin/sete
echo "echo '                 CLIENTES EXPIRANDO                  '" >> /usr/bin/sete
echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/sete
echo "echo '====================================================='" >> /usr/bin/sete
echo 'printf "${NORMAL}"' >> /usr/bin/sete

echo > /usr/bin/exp
echo '#!/bin/bash' > /usr/bin/exp
echo 'if which tput >/dev/null 2>&1; then
      ncolors=$(tput colors)
fi
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
    RED="$(tput setaf 1)"
    GREEN="$(tput setaf 2)"
    YELLOW="$(tput setaf 3)"
    BLUE="$(tput setaf 4)"
    BOLD="$(tput bold)"
    NORMAL="$(tput sgr0)"
else
    RED=""
    GREEN=""
    YELLOW=""
    BLUE=""
    BOLD=""
    NORMAL=""
fi' >> /usr/bin/exp
echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/exp
echo "echo '====================================================='" >> /usr/bin/exp
echo 'printf "${YELLOW}${BOLD}"' >> /usr/bin/exp
echo "echo '                 CLIENTES EXPIRADOS                  '" >> /usr/bin/exp
echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/exp
echo "echo '====================================================='" >> /usr/bin/exp
echo 'printf "${NORMAL}"' >> /usr/bin/exp

echo > /usr/bin/all
echo '#!/bin/bash' > /usr/bin/all
echo 'if which tput >/dev/null 2>&1; then
      ncolors=$(tput colors)
fi
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
    RED="$(tput setaf 1)"
    GREEN="$(tput setaf 2)"
    YELLOW="$(tput setaf 3)"
    BLUE="$(tput setaf 4)"
    WHITE="$(tput setaf 7)"    
    BOLD="$(tput bold)"
    NORMAL="$(tput sgr0)"
else
    RED=""
    GREEN=""
    YELLOW=""
    BLUE=""
    BOLD=""
    NORMAL=""
fi' >> /usr/bin/all
echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/all
echo "echo '==============================================================================='" >> /usr/bin/all
echo 'printf "${YELLOW}${BOLD}"' >> /usr/bin/all
echo "echo '                                TABELA DE CLIENTES                             '" >> /usr/bin/all
echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/all
echo "echo '==============================================================================='" >> /usr/bin/all
echo 'printf "${YELLOW}${BOLD}"' >> /usr/bin/all
echo "echo ' User            |      Senha      |   Expira       |   Inicio   '" >> /usr/bin/all
echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/all
echo "echo '==============================================================================='" >> /usr/bin/all
echo 'printf "${NORMAL}"' >> /usr/bin/all

chmod +x /usr/bin/all
chmod +x /usr/bin/exp
chmod +x /usr/bin/sete

cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
totalaccounts=`cat /tmp/expirelist.txt | wc -l`
for((i=1; i<=$totalaccounts; i++ ))
       do
       tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
       username=`echo $tuserval | cut -f1 -d:`
       	userexp=`echo $tuserval | cut -f2 -d:`
       userexpireinseconds=$(( $userexp * 86400 ))
       tglexp=`date -d @$userexpireinseconds`             
       tgl=`echo $tglexp |awk -F" " '{print $3}'`
       while [ ${#tgl} -lt 2 ]
       do
           tgl="0"$tgl
       done
       while [ ${#username} -lt 15 ]
       do
           username=$username" "
       done
       bulantahun=`echo $tglexp |awk -F" " '{print $2,$6}'`
       val="$(chage -l $username | grep "Account expires" | awk -F": " '{print $2}')"
       iniciou=`cat /usr/share/info/s | awk '{print $2,$6}' | grep -w $username | awk '{print $2}'`
       senha=`cat /usr/share/info/s | awk '{print $2,$4}' | grep -w $username | awk '{print $2}'`
	echo 'printf "${WHITE}${BOLD}"' >> /usr/bin/all
	echo "echo ' $username |  $senha    |  $val  |  $iniciou '" >> /usr/bin/all
   	 echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/all
	echo "echo '==============================================================================='" >> /usr/bin/all
       echo 'printf "${NORMAL}"' >> /usr/bin/all
       todaystime=`date +%s`
       if [ $userexpireinseconds -ge $todaystime ] ;
           then
           timeto7days=$(( $todaystime + 604800 ))
                if [ $userexpireinseconds -le $timeto7days ]; 
                then 
           echo 'printf "${YELLOW}${BOLD}"' >> /usr/bin/sete                    
           echo "echo ' User: $username Expira em: $val '" >> /usr/bin/sete
           echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/sete                     
           echo "echo '====================================================='" >> /usr/bin/sete
           echo 'printf "${NORMAL}"' >> /usr/bin/sete

                fi
       else
       echo 'printf "${RED}${BOLD}"' >> /usr/bin/exp
       echo "echo ' User: $username Expirado em: $val '" >> /usr/bin/exp
       echo 'printf "${BLUE}${BOLD}"' >> /usr/bin/exp
       echo "echo '====================================================='" >> /usr/bin/exp
       echo 'printf "${NORMAL}"' >> /usr/bin/exp
       passwd -l $username
       fi
       done


