#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

if [ -d /etc/VpsPackdir ]
then
echo ""
else
mkdir /etc/VpsPackdir
fi

if [ -d /etc/VpsPackdir/senha ]
then
echo ""
else
mkdir /etc/VpsPackdir/senha
fi

if [ -d /etc/VpsPackdir/limite ]
then
echo ""
else
mkdir /etc/VpsPackdir/limite
fi

clear
echo -e "\033[1;37m Maxtunnel\033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;33m
[1] limit \033[1;30m(limite de conexoes simultaneas)\033[1;33m
[2] cadastro \033[1;30m(Criar usuarios)\033[1;33m
[3] redefine \033[1;30m(Opções para mudanças no usuario)\033[1;33m
[4] deleteuser \033[1;30m(Deletar, Desconectar, Opções)\033[1;33m
[5] host \033[1;30m(Adicionar hosts aceitos pelo squid )\033[1;33m
[6] monitorar \033[1;30m(IMPORTANTE monitorar conexões por usuarios)\033[0m\033[1;33m
[7] Backup-Users \033[1;30m(Backup dos usuarios para reinstalação futura)\033[1;33m
[8] Rest-Users \033[1;30m(Restaurar usuarios feito backup)\033[1;33m
[9] detalhesuser\033[1;30m(Mostra informações sobre os usuarios !!)\033[1;33m
[10] speedtest \033[1;30m(Teste de conexão [velocidade de banda])\033[1;33m
[11] sshmon \033[1;30m(Mostra informações sobre os usuarios !!)\033[1;33m
[12] opv \033[1;30m(openvpn!!)\033[1;33m
[13] banner \033[1;30m(Banner dropbear)\033[1;33m"

read -p ": " opcao

case $opcao in

 1)
  read -p "Usuario: " user
  read -p "Limite de Conexoes: " limit
  limit $user $limit;;
 2)
  cadastro;;
 3)
  redefine;;
 4)
  deleteuser;;
 5)
 host;;
 6)
  monitorar;;
 7)
  backup-users;;
 8)
  read -p "Em qual diretorio esta o arquivo de Backup: " arq 
  restusers $arq;;
 9)
  detalhesuser;;
 10)
 speedtest;;
  11)
 sshmon;;
  12)
   opv;;
    13)
   banner;;
*)
  id > /dev/null 2> /dev/null
esac
