#!/bin/bash

read -p "Qual o nome do usuario a redefinir: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer não existe"
 sleep 3s
 exit
 fi
if [ "$namer" = "" ]
then
echo "Digite um usuario!"
sleep 3s
exit
fi
echo -e "\033[1;36mOQUE VAI REDEFINIR DE \033[1;31m $namer \033[1;36m???"
echo -e " "
echo -e "\033[1;33m1) Numero de logins de\033[1;31m $namer \033[1;33m?
2) Data de expiraçao de\033[1;31m $namer \033[1;33m?
3) Mudar senha de\033[1;31m $namer \033[1;33m?"
echo -e "\033[1;36m"
read -p "opção: " option
echo -e "\033[0m"
if [ $option -eq 1 ]; then
read -p "Qual o novo limite de logins?: " lim
liml="$lim"
echo "$liml" > /etc/VpsPackdir/limite/$namer
echo -e "\033[1;31mO NOVO LIMITE AGORA E $liml\033[0m"
###limite $namer $liml
sleep 4s
exit 0
fi

if [ $option -eq 2 ]; then
echo -e "\033[1;36mDIGITE A NOVA DATA EM NUMEROS\033[0m"
echo -e "\033[1;36mDIA?\033[0m"
read -p ": " dia
echo -e "\033[1;36mMES?\033[0m"
read -p ": " mes
echo -e "\033[1;36mANO?\033[0m"
read -p ": " ano
date="$ano/$mes/$dia"
chage -E $date $namer 2> /dev/null
echo -e "\033[1;31mUsuario $namer Date: $date\033[0m"
sleep 1s
exit
fi

if [ $option -eq 3 ]
then
read -p "Qual a nova senha para $namer: " senha
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$namer
echo "Nova senha aplicada"
sleep 1s
exit
fi

echo -e "essa opçao não existe\033[0m"
sleep 1s
exit
