#!/bin/bash

read -p "Qual o nome do usuario a redefinir: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer não existe"
 exit
 fi
clear
echo -e "\033[1;26mO que vc deseja redefinir ?
1) Numero de logins
2) Data de expiraçao
3) Mudar senha do usuario"
read -p "opção: " option
if [ $option -eq 1 ]; then
read -p "Qual o novo limite de logins: " liml
rm /etc/usuarios/$namer.sh
rm /etc/tempo/$namer.sh
limit $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
senha=`cat /usr/share/info/s | grep -w "User: $namer"  | awk -F"senha: " '{print $2}' | awk  '{print $1}'`
echo "Quantos dias? "
read -p " " daysrnf
date=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")

chage -E $date $namer 2> /dev/null
echo -e "$senha\n$senha\n"|passwd $namer &> /dev/null
				clientesctl &> /dev/null
echo -e "\033[1;31mCONTA RENOVADA COM SUCESSO!  
Usuario: $namer
Expira em: $datexp\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "Qual a nova senha para $namer: " senha
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$namer
echo "Nova senha aplicada"
exit
fi
echo -e "essa opçao não existe\033[0m"
